[package]
name = "pgqueuer-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "core_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
